version: "3"
services:
  python:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/home/hiroki/code
    environment:
      DISPLAY: host.docker.internal:0.0
    command: sleep infinity
